version: "3.9"
services:
  mariadb:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prestashop
    volumes:
      - ./.docker/data/mariadb/:/var/lib/mariadb
      - ./.docker/logs/mariadb/:/var/log/mariadb
    ports:
      - "3308:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    env_file:
      - .env
    environment:
      PMA_HOST: mariadb
      VIRTUAL_HOST: phpmyadmin.test

  app_dev:
    build: .
    environment:
      - VIRTUAL_HOST=prestashop.test
    volumes:
      - ./:/var/www/html:rw
    restart: always
    ports:
      - 9080:80
    links:
      - "mariadb"
